spring.application.name=demo
# 1. La dirección (URL) de lu base de datos en Render
spring.datasource.url=jdbc:postgresql://@dpg-daqmgt0u01pc73f874d0-a.virginia-postgres.render.com/wiki_db_80x4
# 2. Nombre de usuario
spring.datasource.username=astral_admin

# 3. Contraseña secreta
spring.datasource.password=ehofMrnxX44c32sQsJPQfp3MRRNNiuYh
# 4. Le decimos explícitamente el "dialecto" para que no intente adivinarlo (ESTO SOLUCIONA TU ERROR)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 5. Le indicamos el driver exacto de conexión
spring.datasource.driver-class-name=org.postgresql.Driver

# 6. Regla vital del profesor: Actualiza la base de datos automáticamente si cambias el Model
spring.jpa.hibernate.ddl-auto=update

# 7. Herramienta de estudio: Imprime en la terminal el código SQL que Java hace por detrás
spring.jpa.show-sql=true