spring.application.name=demo
# 1. La dirección (URL) de lu base de datos en Render
spring.datasource.url=jdbc:postgresql://<TU_HOST_DE_RENDER>/<TU_BASE_DE_DATOS>?sslmode=require

# 2. Nombre de usuario
spring.datasource.username=<TU_USUARIO>

# 3. Contraseña secreta
spring.datasource.password=<TU_CONTRASEÑA>